train_split: 0.8
img_height: 224
img_width: 224
batch_size: 32
num_classes: 3
epochs: 20
learning_rate: 0.001
dropout_rate: 0.2
model_save_path: "models/best_model.h5"
class_names: ['no_damage', 'damage', 'useless']